---
title: "Stokes cut comparer"
output:
  flexdashboard::flex_dashboard:
    source_code: https://github.com/bcgov/compare_excel
    orientation: columns
runtime: shiny
resource_files:
- data/industry_mapping_2025_with_stokes_agg.xlsx
- out/cagrs.rds
- out/industry_shares.rds
- out/internal_vs_stokes.rds
- out/joined.rds
- out/rtra_data.rds
- out/region_shares.rds
- out/stokes_regional_diff.rds
- R/functions.R
---

```{r, include=FALSE}
library(tidyverse)
library(here)
library(readxl)
library(janitor)
library(conflicted)
library(htmlwidgets) #for function onRender
conflicts_prefer(dplyr::filter)
options(scipen = 999)
min_abs_original <- 10
#functions-----------------------
my_dt <- function(tbbl) {
  DT::datatable(tbbl,
                extensions = "Buttons",
                rownames = FALSE,
                filter="top",
                options = list(
                  columnDefs = list(list(className = "dt-center", targets = "_all")),
                  paging = TRUE,
                  scrollX = TRUE,
                  scrollY = TRUE,
                  searching = TRUE,
                  ordering = TRUE,
                  dom = "Btip",
                  buttons = list(
                    list(extend = "csv", filename = "lmo_2_stokes_industry_mapping"),
                    list(extend = "excel", filename = "lmo_2_stokes_industry_mapping")
                  ),
                  pageLength = 64,
                  lengthMenu = c(3, 5)
                )
  )
}
cagr_plot <- function(tbbl, xvar, yvar, highlight_industry){
  filtered <- tbbl|>
    filter(industry==highlight_industry)
  plt <- ggplot(cagrs, aes({{  xvar  }}, {{  yvar  }},
                           text=paste0("Industry: ",
                                       industry,
                                       "\n Internal CAGR = ",
                                       scales::percent({{  xvar  }}, accuracy = .1),
                                       "\n Stokes CAGR = ",
                                       scales::percent({{  yvar  }}, accuracy = .1))))+
    geom_abline(slope=1, intercept = 0, colour="white", lwd=1.5)+
    geom_point(data=filtered, size=4, colour="red", alpha=.5)+
    geom_point(alpha=.5)+
    scale_x_continuous(labels=scales::percent)+
    scale_y_continuous(labels=scales::percent)+
    labs(x="internal forecast",
         y="stokes forecast")
  plotly::ggplotly(plt, tooltip="text")
}
```

```{r}
#load data----------------------
joined <- read_rds(here("out","joined.rds"))
internal_vs_stokes <- read_rds(here("out","internal_vs_stokes.rds"))
cagrs <- read_rds(here("out","cagrs.rds"))
mapping <- read_excel(here("data","industry_mapping_2025_with_stokes_agg.xlsx"))
rtra_data <- read_rds(here("out","rtra_data.rds"))
industry_shares <- read_rds(here("out","industry_shares.rds"))|>
  filter(when>2001)

if(length(unique(industry_shares$industry))>30){
  industry_shares <- industry_shares|>
    mutate(short_industry=str_trunc(industry, 20, "right"))
}else{
  industry_shares <- industry_shares|>
    mutate(short_industry=industry)
}
region_shares <- read_rds(here("out","region_shares.rds"))
files <- sort(unique(joined$which_file), decreasing = TRUE)
stokes_regional_diff <- read_rds(here("out","stokes_regional_diff.rds"))
detailed_to_stokes <- mapping|>
  select(lmo_detailed_industry, stokes_industry)|>
  distinct()
```

Comparison with previous cut
=====================================  

Inputs {.sidebar data-width=400}
-------------------------------------

*  This app allows one to visualize what has changed between Stokes cuts, and how employment compares with our internal forecast.
*  The heatmap on this page illustrates the symmetric percent change between the current and last cut:
$$\%\Delta = \frac{new-old}{\frac{new+old}{2}}*100$$
*  If new+old=0, the magnitude of the percent change is set to 200.
*  Red indicates the current cut is larger than the last cut, blue smaller.
*  White indicates censoring, so very large percent changes do not swamp smaller changes. 
*  You can zoom in by highlighting (click-dragging) a region of the heatmap. 
*  You can **CLICK** on a row in the heatmap to see the underlying data.
*  To zoom back out double click anywhere in the heatmap.


```{r}
selectInput(
  "file",
  "Select an excel file to compare",
  files,
  selected = files[1]
)

filtered <- reactive({
  joined|>
    filter(which_file==input$file)
})

renderUI({#need the render UI because the list of choices depends on the excel file
selectInput(
  "sheet",
  "Select a sheet to compare",
  unique(filtered()$sheet),
  selected = unique(filtered()$sheet)[1]
)
})

checkboxInput("origin", "Are you Sazid? (should y axis include the origin)", value = FALSE)

sliderInput(
  "percent_less",
  "Show |percent_change| larger than this as white: ",
  100,
  min = 10,
  max = 200,
  step = 1
)
#reactive elements------------------------------------------
reactive_base <- reactive({
  joined|>
    select(-cagr)|>
    filter(which_file==input$file, 
           sheet==input$sheet)
})

reactive_tbbl <- reactive({
   tbbl <- reactive_base()|>
    ungroup()|>
    filter(series=="new_value")|>
    select(when, variable, percent_change)|>
    filter(abs(percent_change)<input$percent_less)|>
    pivot_wider(names_from = "when", values_from = "percent_change")|>
    column_to_rownames("variable")|>
    remove_empty("rows")|>
    as.matrix()
   
    row_order <- order(rowMeans(abs(tbbl)))
    tbbl[row_order, ]
})

reactive_show_labels <- reactive({
  if_else(nrow(reactive_tbbl())<80, TRUE, FALSE)
})

reactive_compare <- reactive({
  joined|>
  filter(which_file==input$file,
         sheet==input$sheet)
})

reactive_wide <- reactive({
  wide <- internal_vs_stokes|>
  ungroup()|>
  select(industry, when, percent_change)|>
  filter(industry!="Total")|>
  distinct()|>
  pivot_wider(id_cols = industry, names_from = "when", values_from = "percent_change")|>
  column_to_rownames("industry")|>
  as.matrix()
   
  row_order <- order(rowMeans(abs(wide)))  
  wide[row_order, ]
})

reactive_tbbl2 <- reactive({
 internal_vs_stokes|>
    filter(industry==rev(rownames(reactive_wide()))[input$point2$y])
})
 
reactive_rtra <- reactive({
  rtra_data|>
    filter(industry==rev(rownames(reactive_wide()))[input$point2$y])
})
```
 
Column {data-width=550}
-------------------------------------
    
### `r renderUI({ paste(input$file, input$sheet, sep=": ")})`
    
```{r, fig.retina=2}
js <- "
function(el, x) {
  el.on('plotly_click', function(d) {
    var point = d.points[0];
    Shiny.setInputValue('point', {y: point.y});
  });
}"

plotly::renderPlotly({
  req(input$file)
  req(input$sheet)
  heatmaply::heatmaply_cor(reactive_tbbl(),
                         dendrogram=FALSE,
                         key.title="percent change",
                         showticklabels = c(FALSE, reactive_show_labels()))|>
    plotly::config(displayModeBar = FALSE)|>
  onRender(js)
})
```

Column {data-width=450}
-------------------------------------

### A plot of the original and new values of row...

```{r, fig.retina=2}
plotly::renderPlotly({
  req(input$point)
  plt <- reactive_compare()|>
    filter(variable==rev(rownames(reactive_tbbl()))[input$point$y])|>
    ggplot(aes(when,
               value,
               colour=series,
               group=series,
               text=paste0("Year: ",
                            when,
                            "\n Series: ",
                             series,
                            "\n Value: ",
                             scales::comma(value, accuracy = .1),
                            "\n CAGR: ",
                            scales::percent(cagr, accuracy = .1))))+
    geom_line()+
    scale_colour_brewer(palette = "Dark2")+
    scale_y_continuous(labels = scales::comma)+
    labs(title=rev(rownames(reactive_tbbl()))[input$point$y],
         x=NULL,
         y=NULL,
         colour=NULL)
 
  if(input$origin==TRUE){
    plt <- plt+ 
      expand_limits(y = 1)
  }
  plotly::ggplotly(plt, tooltip="text")%>%
    plotly::layout(hovermode = "x")
})
```

### The data:

```{r}
DT::renderDT({ 
  req(input$point)
  reactive_base()|>
    filter(variable==rev(rownames(reactive_tbbl()))[input$point$y])|>
    ungroup()|>
    pivot_wider(names_from = "series", values_from = "value")|>
    select(when, new_value, original_value, percent_change)|>
    mutate(percent_change=round(percent_change, 1),
           new_value=scales::comma(new_value, accuracy = .1),
           original_value=scales::comma(original_value, accuracy = .1))|>
    DT::datatable( rownames = FALSE)
})
```

Comparison with internal
=====================================  

Column 
-------------------------------------
    
### Degree of difference between internal and stokes:  **CLICK** on row to choose industry
    
```{r, fig.retina=2}
js2 <- "
function(el, x) {
  el.on('plotly_click', function(d) {
    var point = d.points[0];
    Shiny.setInputValue('point2', {y: point.y});
  });
}"
plotly::renderPlotly({
heatmaply::heatmaply_cor(reactive_wide(),
                         dendrogram=FALSE,
                         key.title="percent change",
                         showticklabels = c(FALSE, TRUE))|>
    plotly::config(displayModeBar = FALSE)|>
  onRender(js2)
})
```
 
Column{.tabset}
------------------------------------- 
 
### `r renderUI({rev(rownames(reactive_wide()))[input$point2$y]})` relative to LFS Data


```{r, fig.retina=2}
plotly::renderPlotly({
  req(input$point2)
  plt <- ggplot()+
    geom_line(data=reactive_tbbl2(), 
              mapping= aes(when, 
                           value, 
                           colour=series,
                           group=series,
                           text=paste(
                             "Date: ",
                             when,
                             "\n Series: ",
                             series,
                             "\n Value: ",
                             scales::comma(value, accuracy = .1),
                             "\n CAGR: ",
                             scales::percent(cagr, accuracy = .1)
                            )
                           )
              )+
    geom_line(data=reactive_rtra(), 
              mapping= aes(when, 
                           value, 
                           colour=series,
                           group=series,
                           alpha=alpha,
                           text=paste("Date: ",
                                      when,
                                      "\n Series: ",
                                      series,
                                      "\n Value: ",
                                      scales::comma(value, accuracy = .1),
                                      "\n CAGR: ",
                                      scales::percent(cagr, accuracy = .1)
                                      )))+
    scale_y_continuous(labels = scales::comma)+
    scale_colour_brewer(palette = "Dark2")+
    scale_alpha_identity()+
    labs(x=NULL,
         y=NULL,
         colour=NULL)

  if(input$origin==TRUE){
    plt <- plt+
      expand_limits(y = 0)
  }
  plotly::ggplotly(plt, tooltip="text")%>%
  plotly::layout(hovermode = "x")
})
```

### First five year CAGRs 

```{r, fig.retina=2}
plotly::renderPlotly({
  req(input$point2)  
  cagr_plot(cagrs, internal_cagr_ffy, stokes_cagr_ffy, rev(rownames(reactive_wide()))[input$point2$y])
})  
``` 


### Second five year CAGRs

```{r, fig.retina=2}
plotly::renderPlotly({
  req(input$point2)    
  cagr_plot(cagrs, internal_cagr_sfy, stokes_cagr_sfy, rev(rownames(reactive_wide()))[input$point2$y])
})  
```

### Ten year CAGRs
  
```{r, fig.retina=2}
plotly::renderPlotly({
  req(input$point2)    
  cagr_plot(cagrs, internal_cagr_ty, stokes_cagr_ty, rev(rownames(reactive_wide()))[input$point2$y])
})  
```




Industry by Region
===================================== 

Inputs {.sidebar}
-------------------------------------

```{r}
selectInput(
  "industry",
  "Select an industry",
  unique(region_shares$industry),
  selected = unique(region_shares$industry)[1]
)

selectInput(
  "what",
  "Do you want to plot counts or shares?",
  c("count","share"),
  "shares"
)

```

Column 
------------------------------------- 

### `r renderUI({input$industry})`

```{r, fig.retina=2}
plotly::renderPlotly({
  plt <- region_shares|>
    filter(industry==input$industry,
           name==input$what)|>
    ggplot(aes(when, 
               value, 
               colour=series,
               group=series,
               alpha=alpha,
               text=paste0("year: ",
                           when,
                           "\n series: ",
                           series,
                           "\n value: ",
                           if(input$what=="count"){
                             scales::comma(value, accuracy = .1)
                           }else{
                             scales::percent(value, accuracy = .1)
                           }
                           ,
                           "\n CAGR: ",
                            scales::percent(cagr, accuracy = .1))))+
    geom_line()+
    facet_wrap(~fct_reorder(bc_region, value, max, .desc=TRUE), scales="free")+
    labs(x=NULL,
         y=NULL)+
    theme(legend.position='none')+
    scale_colour_brewer(palette = "Dark2")+
    scale_alpha_identity()
  
 if(input$origin==TRUE){
    plt <- plt+ 
      expand_limits(y = 0)
  }   
  if(input$what=="share"){
    plt <- plt+
      scale_y_continuous(labels=scales::percent)
  }else{
    plt <- plt+
      scale_y_continuous(labels=scales::comma)
  }
plotly::ggplotly(plt, tooltip = "text")    
})
```


Region by Industry
=====================================  

Inputs {.sidebar}
-------------------------------------

```{r}
selectInput(
  "region",
  "Select a region",
  unique(industry_shares$bc_region),
  selected = unique(industry_shares$bc_region)[1]
)

selectInput(
  "what2",
  "Do you want to plot counts or shares?",
  c("count","share"),
  "shares"
)

```

Column
------------------------------------- 

### `r renderUI({input$region})`

```{r, fig.retina=2}
plotly::renderPlotly({
  plt <- industry_shares|>
    filter(bc_region==input$region,
           name==input$what2)|>
    ggplot(aes(when, 
               value, 
               colour=series,
               group=series,
               alpha=alpha,
               text=paste0("year: ",
                           when,
                           "\n series: ",
                           series,
                           "\n value: ",
                           if(input$what2=="count"){
                             scales::comma(value, accuracy = .1)
                           }else{
                             scales::percent(value, accuracy = .1)
                           },
                           "\n CAGR: ",
                           scales::percent(cagr, accuracy = .1)
                           )
               )
           )+
    geom_line()+
    facet_wrap(~fct_reorder(short_industry, value, max, .desc=TRUE), scales="free_y")+
    labs(x=NULL,
         y=NULL)+
    scale_colour_brewer(palette = "Dark2")+
    scale_alpha_identity()+
    theme(legend.position='none',
    panel.spacing.x = unit(-1, "lines"), 
    panel.spacing.y = unit(.25, "lines"),      
    text=element_text(size=9))
  
if(input$origin==TRUE){
    plt <- plt+ 
      expand_limits(y = 0)
}  

if(input$what2=="share"){
  plt <- plt+
    scale_y_continuous(labels=scales::percent)
}else{
  plt <- plt+
    scale_y_continuous(labels=scales::comma)
}  

plotly::ggplotly(plt, tooltip = "text")|>
    plotly::config(
      toImageButtonOptions = list(
        format = "svg",
        width = 1600,
        height = 900
      )
    ) 
})
```

Regional heatmaps
=======================================

Inputs {.sidebar}
-------------------------------------

```{r}
selectInput(
  "industry2",
  "Select an industry",
  unique(stokes_regional_diff$industry),
  selected = unique(stokes_regional_diff$industry)[1]
)
```


Column
------------------------------------- 

### Regional cut comparison for `r renderUI({input$industry2})`

```{r, fig.retina=2}
renderPlot({
 stokes_regional_diff|>
  mutate(when=as.character(when))|>
  filter(industry==input$industry2)|>
  ggplot(aes(when, bc_region))+
  geom_tile(aes(fill=scaled_difference), colour="black")+
  geom_text(aes(label=paste0(scales::comma(difference, accuracy = .1),
                             "\n",
                             "(",scales::percent(percent_difference, accuracy = .1),
                             ")",
                             "\n",
                             scales::comma(new, accuracy = .1)
                             )),
            size=5)+
  colorspace::scale_fill_continuous_diverging()+
  theme_minimal()+
  labs(x=NULL,
       y=NULL,
       fill=NULL,
       title="level differences, % differences, and new levels")+ 
    theme(text=element_text(size=20))
})
```


LMO Stokes Mapping
===================================== 

```{r}
my_dt(detailed_to_stokes)
```



